language: bash
sudo: false

before_install:
  - echo "before_install"

install:
  - echo "install"
  # Download Terraform
  - curl --silent --output terraform.zip https://releases.hashicorp.com/terraform/0.11.2/terraform_0.11.2_linux_amd64.zip
  - sha256sum terraform.zip  | grep "f728fa73ff2a4c4235a28de4019802531758c7c090b6ca4c024d48063ab8537b" -q
  - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
  - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
  - terraform -v
  # Download json parser
  - curl -sO http://stedolan.github.io/jq/download/linux64/jq
  - chmod +x $PWD/jq

script:
  - echo 'script'

jobs:
  include:
    - stage: test
      script:
        - echo 'Terraform Format Check'
        - terraform fmt -check=true
    - # stage name not required, will continue to use `test`
      script:
        - echo 'JSON Format Check'
        - find $TRAVIS_BUILD_DIR -name '*.json' -type f -print0 | xargs -0 -n1 -I {} -t jq --exit-status . {} > /dev/null
