language: bash
sudo: false

env:
  global:
    - FIND_JSON="find $TRAVIS_BUILD_DIR -name '*.json' -type f -print0"
    - XARGS_CMD="xargs -0 -n1 -I {} -t"
    - REPO="${TRAVIS_REPO_SLUG#*/}"
    - OWNER=plus3it
    - DEPLOY_SLUG=$OWNER/$REPO

before_script:
  - echo $JOB
  - echo $TESTCOMMAND

script:
  - bash -c "$TESTCOMMAND"

jobs:
  include:
    - stage: test
      # Begin Terraform Format Verification Job
      env:
        - JOB="Terraform Format Verification"
        - TESTCOMMAND="terraform fmt -check=true"
      before_script:
        # Download Terraform
        - TERRAFORM_VERSION=$(curl -sSL https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
        - TERRAFORM_URL="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
        - echo "TERRAFORM_URL=${TERRAFORM_URL}"
        - curl -sSL -o terraform.zip "$TERRAFORM_URL"
        - unzip terraform.zip && rm -f terraform.zip
        - chmod +x terraform
        - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin ; mv terraform ${HOME}/bin/
        - terraform -v
    - stage: test
      # Begin JSON Verification Job
      env:
        - JOB="JSON Syntax Verification"
        - TESTCOMMAND="$FIND_JSON | $XARGS_CMD jq --exit-status . {} > /dev/null"
    - stage: test
      # Begin JSON Diff Job
      env:
        - JOB="JSON Lint/Format Verification"
        - TESTCOMMAND="$FIND_JSON | $XARGS_CMD bash -c 'cmp {} <(jq --indent 4 -S . {})'"
    - stage: deploy
      if: branch = master AND type = push AND repo = env(DEPLOY_SLUG)
      env:
        - JOB="Deploy to GitHub Releases"
        - PRIOR_VERSION=$(git describe --abbrev=0 --tags)
        - RELEASE_VERSION=$(grep current_version <$TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //')
        - RELEASE_BODY="* [$REPO v$RELEASE_VERSION changes](https://github.com/$OWNER/$REPO/compare/$PRIOR_VERSION...$RELEASE_VERSION)"
      before_script:
        - echo PRIOR_VERSION=$PRIOR_VERSION
        - echo RELEASE_VERSION=$RELEASE_VERSION
        - echo RELEASE_BODY=$RELEASE_BODY
      script:
        - test "$PRIOR_VERSION" = "$RELEASE_VERSION" && travis_terminate || echo "Deploying new version..."
      deploy:
        provider: releases
        api_key:
          secure: R/w2zqcS5EQI8TrCbDuLJUIox6hhJYyOnVYCzjO5pDh2CnzC8ohWk1XXoLMJAzz6Nnk/WG4PcowTOKVU5JULXzWjoAuNPEMhdI1AQqv5FGQH2dHJ20sq4bvEkRzQbYn76oJtaer2alxGeKK1/ArwkpuSNYPI4kBS1IUOtDbm7ALEEGaY7IOsECcVuwT5Xsd3PTULTWuY61yWmpjsF/+CDiHEVgRdvAJxbrfa6e4k7gh0iFkWqk/4Q/8oVbhjUaljkKmH/5LP/jl2LymbkzH5qolT2uXpH4VrN4IC0NjewS/npV2PX0D0+we0iZAtlyOycnwHyu1te+77ibytwaG2Ls5/8Ydzyp9wqQ4rkMt2YByEnZ/386FK20Y2LxTD8hEFlJjUGXbXmSTtfOjTXqMTkhRASRntTtQ6t7i4w0fosg4/DqXoJXr48eVxf7NN70ismoMuSeZfCGYNsEW4xx4eMF9pTcpV+ApIVl2Jsv+gtRBozj/uUfg3n8BH99DmWwlAz3mYiMhhkWi89hk1Mx1Gbt2vPgJOZCukANbIIfhdwcWeHwlKWsdagwxoMFd3+WioRHM9E0PJeOR9yCC/Fu/JRGoqJIdydyC6BkxWa8J254fRefEWCamjBBhvpKCk8wT66AW8BOSTHUXls++qjS6/+nKhAcU3z+RqxpCL8X67eQc=
        name: $RELEASE_VERSION
        tag_name: $RELEASE_VERSION
        body: $RELEASE_BODY
        draft: false
