language: bash

env:
  global:
    - REPO="${TRAVIS_REPO_SLUG#*/}"
    - OWNER=plus3it
    - DEPLOY_SLUG=$OWNER/$REPO
    - RELEASE_VERSION=$(grep -E '^current_version' $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //')

jobs:
  include:
    - stage: test
      env:
        - JOB="Terraform Format Verification"
      before_script:
        - TERRAFORM_VERSION=$(curl -sSL https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
        - TERRAFORM_URL="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
        - echo "TERRAFORM_URL=${TERRAFORM_URL}"
        - curl -sSL -o terraform.zip "$TERRAFORM_URL"
        - unzip terraform.zip && rm -f terraform.zip
        - chmod +x terraform
        - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin ; mv terraform ${HOME}/bin/
        - terraform -v
      script:
        - make tf.lint
    - stage: test
      env:
        - JOB="JSON Lint/Format"
      install:
        - jq --version
      script:
        - make json.lint
    - stage: test
      env:
        - JOB="CFN Version Validation"
      install:
        - jq --version
      script:
        - make cfn.version VERSION=$RELEASE_VERSION
    - stage: test
      env:
        - JOB="CFN Lint"
      install:
        - pip install -r _requirements/cfn-lint.txt
        - cfn-lint --version
      language: python
      script:
        - make cfn.lint
    - stage: deploy
      if: branch = master AND type = push AND repo = env(DEPLOY_SLUG)
      env:
        - JOB="Deploy to GitHub Releases"
        - PRIOR_VERSION=$(git describe --abbrev=0 --tags)
        - RELEASE_BODY="* [$REPO v$RELEASE_VERSION changes](https://github.com/$OWNER/$REPO/compare/$PRIOR_VERSION...$RELEASE_VERSION)"
      before_script:
        - echo PRIOR_VERSION=$PRIOR_VERSION
        - echo RELEASE_VERSION=$RELEASE_VERSION
        - echo RELEASE_BODY=$RELEASE_BODY
      script:
        - test "$PRIOR_VERSION" = "$RELEASE_VERSION" && travis_terminate || echo "Deploying new version..."
      deploy:
        provider: releases
        api_key:
          secure: R/w2zqcS5EQI8TrCbDuLJUIox6hhJYyOnVYCzjO5pDh2CnzC8ohWk1XXoLMJAzz6Nnk/WG4PcowTOKVU5JULXzWjoAuNPEMhdI1AQqv5FGQH2dHJ20sq4bvEkRzQbYn76oJtaer2alxGeKK1/ArwkpuSNYPI4kBS1IUOtDbm7ALEEGaY7IOsECcVuwT5Xsd3PTULTWuY61yWmpjsF/+CDiHEVgRdvAJxbrfa6e4k7gh0iFkWqk/4Q/8oVbhjUaljkKmH/5LP/jl2LymbkzH5qolT2uXpH4VrN4IC0NjewS/npV2PX0D0+we0iZAtlyOycnwHyu1te+77ibytwaG2Ls5/8Ydzyp9wqQ4rkMt2YByEnZ/386FK20Y2LxTD8hEFlJjUGXbXmSTtfOjTXqMTkhRASRntTtQ6t7i4w0fosg4/DqXoJXr48eVxf7NN70ismoMuSeZfCGYNsEW4xx4eMF9pTcpV+ApIVl2Jsv+gtRBozj/uUfg3n8BH99DmWwlAz3mYiMhhkWi89hk1Mx1Gbt2vPgJOZCukANbIIfhdwcWeHwlKWsdagwxoMFd3+WioRHM9E0PJeOR9yCC/Fu/JRGoqJIdydyC6BkxWa8J254fRefEWCamjBBhvpKCk8wT66AW8BOSTHUXls++qjS6/+nKhAcU3z+RqxpCL8X67eQc=
        name: $RELEASE_VERSION
        tag_name: $RELEASE_VERSION
        body: $RELEASE_BODY
        draft: false
