language: bash
sudo: false

env:
  - FIND_JSON="find $TRAVIS_BUILD_DIR -name '*.json' -type f -print0"

before_install:
  - echo 'before_install'

install:
  - echo 'install'

jobs:
  include:
    - stage: test
      # Begin Terraform Format Verfiication Job
      before_script:
        # Download Terraform
        - curl --silent --output terraform.zip https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
        - sha256sum terraform.zip  | grep "6b8a7b83954597d36bbed23913dd51bc253906c612a070a21db373eab71b277b" -q
        - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
        - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
        - terraform -v
      script:
        - echo 'Terraform Format Check'
        - terraform fmt -check=true
    - # Begin JSON Verification Job
      before_script:
        # Download JSON Parser - JQ
        - curl -sO http://stedolan.github.io/jq/download/linux64/jq
        - chmod +x $PWD/jq
      script:
        - echo 'JSON Format Check'
        - bash -c "$FIND_JSON" | xargs -0 -n1 -I {} -t jq --exit-status . {} > /dev/null
    - # Begin JSON Diff Job
      before_script:
        # Download JSON Parser - JQ
        - curl -sO http://stedolan.github.io/jq/download/linux64/jq
        - chmod +x $PWD/jq
      script:
        - echo 'JSON Diff'
        - bash -c "$FIND_JSON" | xargs -0 -n1 -I {} -t echo "{}" >> $TRAVIS_BUILD_DIR/ci/tmp.txt
        - chmod +x $TRAVIS_BUILD_DIR/ci/json_find_diff.sh
        - bash -c $TRAVIS_BUILD_DIR/ci/json_find_diff.sh
